/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OlvasoiLevelekRouteImport } from './routes/olvasoi-levelek'
import { Route as KozgyulesRouteImport } from './routes/kozgyules'
import { Route as AprohirdetesekRouteImport } from './routes/aprohirdetesek'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VarosSlugRouteImport } from './routes/varos.$slug'
import { Route as KategoriaSlugRouteImport } from './routes/kategoria.$slug'
import { Route as CikkIdRouteImport } from './routes/cikk.$id'

const OlvasoiLevelekRoute = OlvasoiLevelekRouteImport.update({
  id: '/olvasoi-levelek',
  path: '/olvasoi-levelek',
  getParentRoute: () => rootRouteImport,
} as any)
const KozgyulesRoute = KozgyulesRouteImport.update({
  id: '/kozgyules',
  path: '/kozgyules',
  getParentRoute: () => rootRouteImport,
} as any)
const AprohirdetesekRoute = AprohirdetesekRouteImport.update({
  id: '/aprohirdetesek',
  path: '/aprohirdetesek',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VarosSlugRoute = VarosSlugRouteImport.update({
  id: '/varos/$slug',
  path: '/varos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriaSlugRoute = KategoriaSlugRouteImport.update({
  id: '/kategoria/$slug',
  path: '/kategoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CikkIdRoute = CikkIdRouteImport.update({
  id: '/cikk/$id',
  path: '/cikk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aprohirdetesek': typeof AprohirdetesekRoute
  '/kozgyules': typeof KozgyulesRoute
  '/olvasoi-levelek': typeof OlvasoiLevelekRoute
  '/cikk/$id': typeof CikkIdRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/varos/$slug': typeof VarosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aprohirdetesek': typeof AprohirdetesekRoute
  '/kozgyules': typeof KozgyulesRoute
  '/olvasoi-levelek': typeof OlvasoiLevelekRoute
  '/cikk/$id': typeof CikkIdRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/varos/$slug': typeof VarosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aprohirdetesek': typeof AprohirdetesekRoute
  '/kozgyules': typeof KozgyulesRoute
  '/olvasoi-levelek': typeof OlvasoiLevelekRoute
  '/cikk/$id': typeof CikkIdRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/varos/$slug': typeof VarosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aprohirdetesek'
    | '/kozgyules'
    | '/olvasoi-levelek'
    | '/cikk/$id'
    | '/kategoria/$slug'
    | '/varos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aprohirdetesek'
    | '/kozgyules'
    | '/olvasoi-levelek'
    | '/cikk/$id'
    | '/kategoria/$slug'
    | '/varos/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aprohirdetesek'
    | '/kozgyules'
    | '/olvasoi-levelek'
    | '/cikk/$id'
    | '/kategoria/$slug'
    | '/varos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AprohirdetesekRoute: typeof AprohirdetesekRoute
  KozgyulesRoute: typeof KozgyulesRoute
  OlvasoiLevelekRoute: typeof OlvasoiLevelekRoute
  CikkIdRoute: typeof CikkIdRoute
  KategoriaSlugRoute: typeof KategoriaSlugRoute
  VarosSlugRoute: typeof VarosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/olvasoi-levelek': {
      id: '/olvasoi-levelek'
      path: '/olvasoi-levelek'
      fullPath: '/olvasoi-levelek'
      preLoaderRoute: typeof OlvasoiLevelekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kozgyules': {
      id: '/kozgyules'
      path: '/kozgyules'
      fullPath: '/kozgyules'
      preLoaderRoute: typeof KozgyulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprohirdetesek': {
      id: '/aprohirdetesek'
      path: '/aprohirdetesek'
      fullPath: '/aprohirdetesek'
      preLoaderRoute: typeof AprohirdetesekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varos/$slug': {
      id: '/varos/$slug'
      path: '/varos/$slug'
      fullPath: '/varos/$slug'
      preLoaderRoute: typeof VarosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategoria/$slug': {
      id: '/kategoria/$slug'
      path: '/kategoria/$slug'
      fullPath: '/kategoria/$slug'
      preLoaderRoute: typeof KategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cikk/$id': {
      id: '/cikk/$id'
      path: '/cikk/$id'
      fullPath: '/cikk/$id'
      preLoaderRoute: typeof CikkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AprohirdetesekRoute: AprohirdetesekRoute,
  KozgyulesRoute: KozgyulesRoute,
  OlvasoiLevelekRoute: OlvasoiLevelekRoute,
  CikkIdRoute: CikkIdRoute,
  KategoriaSlugRoute: KategoriaSlugRoute,
  VarosSlugRoute: VarosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
